"""Add latest models

Revision ID: 5e3880326ae1
Revises: 1a57f292d639
Create Date: 2025-08-25 01:21:11.896583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e3880326ae1'
down_revision: Union[str, Sequence[str], None] = '1a57f292d639'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chat_usage',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chat_session_id', sa.Integer(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('first_used', sa.DateTime(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['indexed_documents.id'], ),
    sa.PrimaryKeyConstraint('document_id', 'chat_session_id')
    )
    op.add_column('chat_messages', sa.Column('response_time', sa.Float(), nullable=True))
    op.add_column('indexed_documents', sa.Column('file_type', sa.String(), nullable=False))
    op.add_column('indexed_documents', sa.Column('chunks_count', sa.Integer(), nullable=True))
    op.add_column('indexed_documents', sa.Column('processing_status', sa.String(), nullable=True))
    op.add_column('indexed_documents', sa.Column('last_processed', sa.DateTime(), nullable=True))
    op.alter_column('indexed_documents', 'file_size',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.drop_constraint(op.f('indexed_documents_file_path_key'), 'indexed_documents', type_='unique')
    op.create_index(op.f('ix_indexed_documents_file_path'), 'indexed_documents', ['file_path'], unique=True)
    op.drop_column('indexed_documents', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indexed_documents', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_indexed_documents_file_path'), table_name='indexed_documents')
    op.create_unique_constraint(op.f('indexed_documents_file_path_key'), 'indexed_documents', ['file_path'], postgresql_nulls_not_distinct=False)
    op.alter_column('indexed_documents', 'file_size',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('indexed_documents', 'last_processed')
    op.drop_column('indexed_documents', 'processing_status')
    op.drop_column('indexed_documents', 'chunks_count')
    op.drop_column('indexed_documents', 'file_type')
    op.drop_column('chat_messages', 'response_time')
    op.drop_table('document_chat_usage')
    # ### end Alembic commands ###
