"""cascade chat sessions on delete

Revision ID: e9dd4e5fe52a
Revises: a6e828a44710
Create Date: 2025-08-25 05:53:00.683748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9dd4e5fe52a'
down_revision: Union[str, Sequence[str], None] = 'a6e828a44710'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('document_chat_usage_document_id_fkey'), 'document_chat_usage', type_='foreignkey')
    op.drop_constraint(op.f('document_chat_usage_chat_session_id_fkey'), 'document_chat_usage', type_='foreignkey')
    op.create_foreign_key(None, 'document_chat_usage', 'indexed_documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'document_chat_usage', 'chat_sessions', ['chat_session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_chat_usage', type_='foreignkey')
    op.drop_constraint(None, 'document_chat_usage', type_='foreignkey')
    op.create_foreign_key(op.f('document_chat_usage_chat_session_id_fkey'), 'document_chat_usage', 'chat_sessions', ['chat_session_id'], ['id'])
    op.create_foreign_key(op.f('document_chat_usage_document_id_fkey'), 'document_chat_usage', 'indexed_documents', ['document_id'], ['id'])
    # ### end Alembic commands ###
